### ISSUE TITLE
Framework gives ambiguous error message when transform reads incomplete data block

### ISSUE THREAD

**Issue by StevenCTimm** [HEPCloud/decisionengine#4] opened 2018-11-07 21:54 UTC
When a transform is called with an incomplete data block, either one that is totally null or
one that is missing fields that the transform needs, the error message is inaccurate.

2018-11-01 16:52:26,708 - decision_engine - TaskManager - JobClustering - ERROR - exception from JobClustering: name 'V' is not defined

We were not requesting any field called "V" although we were requesting one called "VO"

It would be nice to have a better message for debugging..eventually I figured out that the modified
transform was using two fields that the source was not putting in the data frame (but neither
one of them had a "V" in it.)

**Comment by moibenko** [comment] 2018-11-21 17:10
"V" is the name of the transform class.
The developer of this transform should use more descriptive class name

**Comment by moibenko** [comment] 2018-11-21 17:20
Sorry that was a wrong comment. Here is the correct one:
the output contains the name of transform: "JobClustering" and the detail of the exception: "name 'V' is not defined". This is what is the cause of exception and can not be more descriptive, than given in detail of the exception. This error must be reported to the developer of the JobClustering transform.

**Comment by paragmhashilkar** [comment] 2018-11-27 22:17
!11 Merged. This should print detailed messages and address this issue.

**Closed by paragmhashilkar** 2018-11-27 22:17 UTC
